---
acquisitions:
  uuid:
    - acquisitions.uuid
    - collection.entity
  properties: acquisitions.properties
  relationships:
    acquiree.item.uuid: acquisitions.acquiree
    acquirer.item.uuid: acquisitions.acquirer
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
funds:
  uuid:
    - funds.uuid
    - collection.entity
    - fund_investors.fund
  properties: funds.properties
  relationships:
    venture_firm.item.uuid: funds.venture_firm
    investors.items:
      uuid: fund_investors.investor
      properties: fund_investors.properties
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
funding_rounds:
  uuid:
    - funding_rounds.uuid
    - collection.entity
  properties: funding_rounds.properties
  relationships:
    funded_organization.item.uuid: funding_rounds.funded_organization
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
ipos:
  uuid:
    - ipos.uuid
    - collection.entity
  properties: ipos.properties
  relationships:
    funded_company.items:
      uuid: ipos.funded_company
    stock_exchange.item:
      uuid:
        - ipos.stock_exchange
        - stock_exchanges.uuid
      properties: stock_exchanges.properties
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
organizations:
  uuid:
    - organizations.uuid
    - jobs.employer
    - collection.entity
    - trade.vendor
    - competition.competitor_one
  properties: organizations.properties
  relationships:
    primary_image.item:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
      True: collection.is_primary
    founders.items:
      uuid: jobs.employee
      True: jobs.is_founder
    featured_team.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.person.uuid: jobs.employee
      True: jobs.is_featured
    current_team.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.person.uuid: jobs.employee
    past_team.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.person.uuid: jobs.employee
    board_members_and_advisors.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.person.uuid: jobs.employee
      True: jobs.is_advisory
    offices.items:
      uuid:
        - address.uuid
        - collection.content
      type: collection.type
      properties: address.properties
    headquarters.item:
      uuid:
        - address.uuid
        - collection.content
      type: collection.type
      properties: address.properties
      True: collection.is_primary
    categories.items:
      uuid:
        - category.uuid
        - collection.content
      type: collection.type
      properties: category.properties
    customers.items:
      uuid: trade.customer
    competitors.items:
      uuid: competition.competitor_two
    websites.items:
      uuid:
        - website.uuid
        - collection.content
      type: collection.type
      properties: website.properties
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
people:
  uuid:
    - people.uuid
    - jobs.employee
    - degree.student
    - investments.investor
    - collection.entity
  properties: people.properties
  relationships:
    primary_affiliation.item:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.organization.uuid: jobs.employer
    primary_location.item:
      uuid:
        - location.uuid
        - collection.content
      type: collection.type
      properties: location.properties
      True: collection.is_primary
    primary_image.item:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
      True: collection.is_primary
    websites.items:
      uuid:
        - website.uuid
        - collection.content
      type: collection.type
      properties: website.properties
    degrees.items:
      uuid: degree.uuid
      properties: degree.properties
      relationships.school.uuid: degree.school
    jobs.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.organization.uuid: jobs.employer
    advisory_roles.items:
      uuid: jobs.uuid
      properties: jobs.properties
      relationships.organization.uuid: jobs.employer
      True: jobs.is_advisory
    investments.items:
      uuid: investments.uuid
      properties: investments.properties
      relationships.funding_round.uuid: investments.funding_round
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
products:
  uuid:
    - products.uuid
    - collection.entity
  properties: products.properties
  relationships:
    owner.item.uuid: products.owner
    categories.items:
      uuid:
        - category.uuid
        - collection.content
      type: collection.type
      properties: category.properties
    primary_image.item:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
      True: collection.is_primary
    websites.items:
      uuid:
        - website.uuid
        - collection.content
      type: collection.type
      properties: website.properties
    images.items:
      uuid:
        - images.uuid
        - collection.content
      type: collection.type
      properties: images.properties
    videos.items:
      uuid:
        - videos.uuid
        - collection.content
      type: collection.type
      properties: videos.properties
    news.items:
      uuid:
        - news.uuid
        - collection.content
      type: collection.type
      properties: news.properties
...
