---
version: 1
disable_existing_loggers: False
formatters:
    console_fmt:
        format: "%(name)s - %(levelname)s - %(message)s"
    file_fmt:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console_fmt
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: file_fmt
        filename: "../logs/info.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: file_fmt
        filename: "../logs/error.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    console_logger:
        level: DEBUG
        handlers: [console]
        propagate: no
    file_logger:
        level: INFO
        handlers: [info_file_handler, error_file_handler]

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
...
